import type { Metadata } from "next";
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import "./globals.css";
import QuestionAnswerIcon from '@mui/icons-material/QuestionAnswer';
import { Fab } from "@mui/material";

export const metadata: Metadata = {
  title: "Associated Psychotherapists",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* <Fab 
          color="primary" 
          aria-label="add" 
          style={{ 
            position: 'fixed', 
            bottom: 40, 
            right: 40 
          }}
        >
          <QuestionAnswerIcon />
        </Fab> */}
      </body>
    </html>
  );
}
